name: freemake_page
description: Free Video Convertor page.

maintainers: ["Hossein HassanNejad"]
links: {"GitHub": "https://github.com/husen-hn/freemake_page"}

publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
      - assets/images/
  uses-material-design: true